/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mochilapokemon;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ADRIANFEIJOFAGUNDES
 */
public class MochilaInterfaceGrafica extends javax.swing.JFrame {
	private ArrayList<Pokemon> computador = new ArrayList<>();
	private ArrayList<Pokemon> mochila = new ArrayList<>();
	private DefaultListModel<String> modeloListaComputador;
	private DefaultListModel<String> modeloListaMochila;
	
	
	public MochilaInterfaceGrafica() {
		initComponents();
		
		computador.add(new Pokemon("Charmander","Fogo",1));
		computador.add(new Pokemon("Squirtle","Agua",1));
		computador.add(new Pokemon("Pikachu","Eletrico",1));
		computador.add(new Pokemon("Bulbasaur","Grama",1));
		computador.add(new Pokemon("Ekans","Venenoso",1));
		computador.add(new Pokemon("Mankey","Lutador",1));
		computador.add(new Pokemon("Snorlax","Normal",1));
		computador.add(new Pokemon("Dratini","Dragão",1));
		
		modeloListaComputador = new DefaultListModel<>();
		modeloListaMochila = new DefaultListModel<>();
		
		listBackpack.setModel(modeloListaMochila);
		listComputer.setModel(modeloListaComputador);
		
		for (Pokemon pokemon : computador) {
			modeloListaComputador.addElement(pokemon.getNome());
		}
	}

	public void atualizarLista() {
		modeloListaComputador.clear();
		modeloListaMochila.clear();
		
		for (Pokemon pokemon : computador) {
			modeloListaComputador.addElement(pokemon.getNome());
		}
		
		for (Pokemon pokemon : mochila) {
			modeloListaMochila.addElement(pokemon.getNome());
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        backpackLabel = new javax.swing.JLabel();
        computerLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBackpack = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listComputer = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(102, 255, 102));

        backpackLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backpackLabel.setForeground(new java.awt.Color(0, 0, 0));
        backpackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backpackLabel.setText("Mochila");

        computerLabel.setBackground(new java.awt.Color(0, 0, 0));
        computerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        computerLabel.setForeground(new java.awt.Color(0, 0, 0));
        computerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerLabel.setText("Computador");

        addButton.setText("Adicionar a mochila");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remover da mochila");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listBackpack);

        jScrollPane1.setViewportView(listComputer);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(6, 6, 6))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(computerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backpackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backpackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(computerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        int index = listComputer.getSelectedIndex();
		
	if (index == -1) {
		JOptionPane.showMessageDialog(this, "Escolha um Pokemon");
		return;
	}	
	Pokemon pokemon = computador.get(index);
	
	computador.remove(index);
	mochila.add(pokemon);
	
	atualizarLista();
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
	int index = listBackpack.getSelectedIndex();
		
	if (index == -1) {
		JOptionPane.showMessageDialog(this, "Escolha um Pokemon");
		return;
	}	
	Pokemon pokemon = mochila.get(index);
	
	mochila.remove(index);
	computador.add(pokemon);
	
	atualizarLista();
    }//GEN-LAST:event_removeButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MochilaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MochilaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MochilaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MochilaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MochilaInterfaceGrafica().setVisible(true);
				ArrayList<String> sla = new ArrayList<>();
				
				sla.add("Charmander");
				sla.add("Bulbasaur");
				sla.add("Squirtle");
				sla.add("Pikachu");
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel backpackLabel;
    private javax.swing.JLabel computerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listBackpack;
    private javax.swing.JList<String> listComputer;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables

	
	



}
